name: '[Task] Jira 연동 이슈 등록'
description: 'feature/design/setting/test 관련 이슈를 생성하며, 생성된 이슈는 Jira의 Task와 연동됩니다.'
labels: []
title: '[feature/design/setting/test] 이슈(Task) 제목'
body:
    - type: markdown
      attributes:
          value: |
              ### 이슈 등록 확인사항
              - 이슈 제목의 Prefix는 [feature], [design], [setting], [test] 중 하나를 선택하여 작성해주세요.
              - 이슈의 Label은 Prefix에 맞게 자동으로 설정됩니다.
              ---

    - type: input
      id: parentKey
      attributes:
          label: '상위 에픽 Ticket Number'
          description: '상위 에픽의 Ticket Number를 기입해주세요'
          placeholder: 'PET-1'
      validations:
          required: true

    - type: input
      id: relateKey
      attributes:
          label: '연결된 스토리 Ticket Number'
          description: '연결된 스토리의 Ticket Number를 기입해주세요'
          placeholder: 'PET-10'
      validations:
          required: true

    - type: input
      id: branchName
      attributes:
          label: '자동으로 생성될 branch 이름'
          description: 'ex) feature/login/PET-11 형식으로 생성됩니다.'
          placeholder: 'login'
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: '이슈 내용(Description)'
          description: '이슈에 대해서 설명해주세요'
      validations:
          required: true

    - type: textarea
      id: tasks
      attributes:
          label: '체크리스트(Tasks)'
          description: '해당 이슈에 대해 필요한 세부 작업목록을 작성해주세요'
          value: |
              - [ ] Task1
              - [ ] Task2
      validations:
          required: true

    - type: textarea
      id: references
      attributes:
          label: '참조(References)'
          description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
          value: |
              - Reference1
      validations:
          required: false
