name: '[Common] 일반 이슈 등록'
description: 'Docs/Help/Refactor 관련 이슈를 생성하며, Jira와 연동되지 않는 일반 이슈입니다.'
labels: [Docs]
title: '[Docs/Help/Refactor] 이슈 제목'
body:
    - type: markdown
      attributes:
          value: |
              이슈 제목의 Prefix는 [Docs], [Help], [Refactor] 중 하나를 선택하여 작성해주세요.
              이슈의 Label을 Prefix에 맞게 설정해주세요.

    - type: textarea
      id: description
      attributes:
          label: '이슈 내용(Description)'
          description: '이슈에 대해서 설명해주세요'
      validations:
          required: true

    - type: textarea
      id: tasks
      attributes:
          label: '체크리스트(Tasks)'
          description: '해당 이슈에 대해 필요한 세부 작업목록을 작성해주세요'
          value: |
              - [ ] Task1
              - [ ] Task2
      validations:
          required: true

    - type: textarea
      id: references
      attributes:
          label: '참조(References)'
          description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
          value: |
              - Reference1
      validations:
          required: false
