name: 'Jira 연동 Bug 등록'
description: 'Bugfix 관련 이슈를 생성하며, 생성된 이슈는 Jira의 Bug와 연동됩니다.'
labels: [BugFix]
title: '[BugFix] 버그(Bug) 제목'
body:
    - type: input
      id: parentKey
      attributes:
          label: '상위 작업 Ticket Number'
          description: '상위 작업의 Ticket Number를 기입해주세요'
          placeholder: 'PET-1'
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: '버그 내용(Description)'
          description: '버그에 대해서 설명해주세요'
      validations:
          required: true

    - type: textarea
      id: situation
      attributes:
          label: '재현 상황(Situation)'
          description: '버그 발생 상황에 대해서 단계별로 설명해주세요'
          value: |
              1. Step1
              2. Step2
      validations:
          required: true

    - type: textarea
      id: tasks
      attributes:
          label: '체크리스트(Tasks)'
          description: '버그 수정에 필요한 세부 작업목록을 작성해주세요'
          value: |
              - [ ] Task1
              - [ ] Task2
      validations:
          required: true

    - type: textarea
      id: references
      attributes:
          label: '참조(References)'
          description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
          value: |
              - Reference1
      validations:
          required: false
