name: 'Jira 연동 Task 등록'
description: 'Feature/Style/Setting/Test 관련 이슈를 생성하며, 생성된 이슈는 Jira의 Task와 연동됩니다.'
labels: [Feature]
title: '[Feature/Style/Setting/Test] 이슈(Task) 제목'
body:
    - type: input
      id: parentKey
      attributes:
          label: '상위 작업 Ticket Number'
          description: '상위 작업의 Ticket Number를 기입해주세요'
          placeholder: 'PET-1'
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: '이슈 내용(Description)'
          description: '이슈에 대해서 설명해주세요'
      validations:
          required: true

    - type: textarea
      id: tasks
      attributes:
          label: '체크리스트(Tasks)'
          description: '해당 이슈에 대해 필요한 세부 작업목록을 작성해주세요'
          value: |
              - [ ] Task1
              - [ ] Task2
      validations:
          required: true

    - type: textarea
      id: references
      attributes:
          label: '참조(References)'
          description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
          value: |
              - Reference1
      validations:
          required: false
