import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Toaster } from '@/components/common';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className="antialiased">
                {children}
                <Toaster />
            </body>
        </html>
    );
}
