name: 'Auto Label'
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    add-labels:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              with:
                  script: |
                      const owner = context.repo.owner
                      const repo = context.repo.repo
                      const issue_number = context.issue.number
                      const title = context.payload.issue
                        ? context.payload.issue.title
                        : context.payload.pull_request
                        ? context.payload.pull_request.title
                        : ''

                      if (!title) {
                        console.log('Title is undefined. Skipping label addition.')
                        return
                      }

                      // Label 조건 정의
                      const labelMappings = [
                        { regex: /\[fix\]/i, label: 'fix' },
                        { regex: /\[feature\]/i, label: 'feature' },
                        { regex: /\[design\]/i, label: 'design' },
                        { regex: /\[docs?\]/i, label: 'docs' },
                        { regex: /\[setting\]/i, label: 'setting' },
                        { regex: /\[file\]/i, label: 'file' },
                        { regex: /\[style\]/i, label: 'style' },
                        { regex: /\[refact\]/i, label: 'refact' },
                        { regex: /\[test\]/i, label: 'test' }
                      ]

                      let labels = []

                      for (const mapping of labelMappings) {
                        if (mapping.regex.test(title)) {
                          labels.push(mapping.label)
                        }
                      }

                      if (labels.length > 0) {
                        try {
                          console.log('Attempting to add labels:', labels)
                          for (const label of labels) {
                            const response = await github.rest.issues.addLabels({
                              owner,
                              repo,
                              issue_number,
                              labels: [label]
                            })
                            console.log(`Label added: ${label}`, response)
                          }
                        } catch (error) {
                          console.error('Failed to add labels:', error)
                        }
                      } else {
                        console.log('No matching labels found.')
                      }
