name: 'Create and Link Jira Issue'
on:
    issues:
        types: [opened]

jobs:
    create-and-link-jira-task:
        name: Create and Link Jira Task
        runs-on: ubuntu-latest
        steps:
            - name: Login to Jira
              uses: atlassian/gajira-login@v3
              env:
                  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
                  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

            - name: Checkout main code
              uses: actions/checkout@v4

            - name: Parse Issue Template
              uses: stefanbuck/github-issue-praser@v3
              id: issue-parser
              with:
                  template-path: .github/ISSUE_TEMPLATE/1-task-sync-jira.yml

            - name: Convert Markdown to Jira Syntax
              uses: peter-evans/jira2md@v1
              id: md2jira
              with:
                  input-text: |
                      ### Github Issue Link
                      - ${{ github.event.issue.html_url }}

                      ${{ github.event.issue.body }}
                  mode: md2jira

            - name: Create Jira Task
              id: create-task
              uses: atlassian/gajira-create@v3
              with:
                  project: PET
                  issuetype: Task
                  summary: '${{ github.event.issue.title }}'
                  description: '${{ steps.md2jira.outputs.output-text }}'
                  fields: |
                      {
                        "parent": {
                          "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
                        }
                      }

            - name: Link Task to Story
              id: link-task
              uses: atlassian/gajira-link@v3
              with:
                  issue: '${{ steps.create-task.outputs.issue }}'
                  type: 'Relates'
                  destination-issue: '${{ steps.issue-parser.outputs.issueparser_relateKey }}'

            - name: Log Created and Linked Issue
              run: |
                  echo "Created Jira Task: ${{ steps.create-task.outputs.issue }}"
                  echo "Linked Task ${{ steps.create-task.outputs.issue }} to Story ${{ steps.issue-parser.outputs.issueparser_relateKey }}"

            - name: Create Branch for Task
              run: |
                  git checkout -b ${{ steps.create-task.outputs.issue }}
                  git push origin ${{ steps.create-task.outputs.issue }}

            - name: Update GitHub Issue Title
              uses: actions-cool/issues-helper@v3
              with:
                  actions: 'update-issue'
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: '${{ steps.create-task.outputs.issue }} ${{ github.event.issue.title }}'
