name: 'Create Jira issue check'
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    create-issue:
        name: Create Jira issue
        runs-on: ubuntu-latest
        steps:
            - name: Login
              uses: atlassian/gajira-login@v3
              env:
                  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
                  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

            - name: Determine Issue Type
              id: determine-type
              run: |
                  if [[ "${{ github.event.issue.title }}" =~ ^\[(feature|design|setting|test|fix)\] ]]; then
                    prefix=$(echo "${{ github.event.issue.title }}" | grep -o '^\[[^]]*\]' | tr -d '[]')
                    echo "prefix=$prefix" >> $GITHUB_ENV
                    if [[ "$prefix" == "fix" ]]; then
                      echo "type=Bug" >> $GITHUB_ENV
                    else
                      echo "type=Task" >> $GITHUB_ENV
                    fi
                  else
                        echo "Error: Issue title must start with [feature], [design], [setting], [test], or [fix]." >&2
                        exit 1
                  fi
              shell: bash

            - name: Checkout develop code
              uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Issue Parser
              uses: stefanbuck/github-issue-praser@v3
              id: issue-parser
              with:
                  template-path: .github/ISSUE_TEMPLATE/1-task-sync-jira.yml

            - name: Log Issue Parser and prefix
              run: |
                  echo "Parsed branchName: ${{ steps.issue-parser.outputs.issueparser_branchName }}"
                  echo "Parsed prefix: ${{ env.prefix }}"

            - name: Convert markdown to Jira Syntax
              uses: peter-evans/jira2md@v1
              id: md2jira
              with:
                  input-text: |
                      ### Github Issue Link
                      - ${{ github.event.issue.html_url }}

                      ${{ github.event.issue.body }}
                  mode: md2jira

            - name: Create Issue
              id: create
              uses: atlassian/gajira-create@v3
              with:
                  project: PET
                  issuetype: '${{ env.type }}'
                  summary: '${{ github.event.issue.title }}'
                  description: '${{ steps.md2jira.outputs.output-text }}'
                  fields: |
                      {
                        "parent": {
                          "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
                        }
                      }

            - name: Log created issue
              run: echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"

            - name: Checkout develop code
              uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Create branch with Ticket number
              run: |
                  prefix="${{ env.prefix }}"
                  branch_name="${prefix}/${{ steps.issue-parser.outputs.issueparser_branchName }}/${{ steps.create.outputs.issue }}"

                  if ! [[ "$branch_name" =~ ^[a-zA-Z0-9/_-]+$ ]]; then
                    echo "Error: Invalid branch name $branch_name"
                    exit 1
                  fi
                  git checkout -b "$branch_name"
                  git push origin "$branch_name"

            - name: Update issue title
              uses: actions-cool/issues-helper@v3
              with:
                  actions: 'update-issue'
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: '${{ steps.create.outputs.issue }} ${{ github.event.issue.title }}'
